# Generated by Django 5.2.14 on 2026-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('hide', 'Hide'), ('quarantine', 'Quarantine'), ('restore', 'Restore'), ('delete', 'Delete'), ('purge', 'Purge'), ('rescan', 'Rescan'), ('regenerate_share', 'Regenerate share'), ('resolve_report', 'Resolve report')], max_length=32),
        ),
    ]
