# Generated by Django 5.2.14 on 2026-05-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_alter_moderationaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_abuse_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
