# Generated by Django 5.2.14 on 2026-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_abusereport_assigned_to_abusereport_staff_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='changelog',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='game_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='version',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
