# Generated by Django 5.2.14 on 2026-05-25 08:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fileshare", "0006_add_update_quota_action"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("verified_email"),
                condition=models.Q(("verified_email", ""), _negated=True),
                name="unique_verified_email_ci",
            ),
        ),
    ]
